BOARD_WIDTH_MM = 340
BOARD_HEIGHT_MM = 590
HEIGHT_PADDING_MM = 25  # 25 including both directions

"""
Ran the following code:
for _ in range(100):
    current_voltage = step(board, 5, 3, steps_per_second, LEFT, current_voltage)
and got 19.5 mm movement for steps_per_second = 100
"""
STEPS_PER_SECOND = 10
CM_PER_STEPS = 7.9 / 400
MM_PER_STEP = 0.2019
DEG_PER_STEP_LIN = 360 / 400
DEG_PER_STEP_ANG = 383 / 400
DEG_PER_STEP_ANG = 360 / 400
MAX_TARGET = 126 / MM_PER_STEP
PLAYER_WIDTH_MM = 20
HALF_PLAYER_WIDTH_MM = PLAYER_WIDTH_MM / 2
CV_GOALIE_DISTANCE = (7, 144) # range of motion from 7 to 144 by cv recognition
def CV_MM_TO_STEPS(mm: int) -> int:
    mm -= CV_GOALIE_DISTANCE[0]
    return mm // ((CV_GOALIE_DISTANCE[1] - CV_GOALIE_DISTANCE[0]) / 620)

DISTANCE_BETWEEN_PLAYERS_MM = 90
MOVEMENT_RANGE_MM = 125
PLAYERS_RANGES = [
    (0, MOVEMENT_RANGE_MM + HALF_PLAYER_WIDTH_MM),
    (DISTANCE_BETWEEN_PLAYERS_MM, DISTANCE_BETWEEN_PLAYERS_MM + MOVEMENT_RANGE_MM + HALF_PLAYER_WIDTH_MM),
    (2 * DISTANCE_BETWEEN_PLAYERS_MM, 2 * DISTANCE_BETWEEN_PLAYERS_MM + MOVEMENT_RANGE_MM + HALF_PLAYER_WIDTH_MM),
]


def MM_TO_STEPS(mm: int):
    # return round((mm + 0.2757) / 0.2148)
    # return round((mm) / 0.2148)
    # return round((mm) / 0.2302)
    return round((mm) / 0.2)


MAX_VELOCITY = 100000
VELOCITY = 8000

L_STEP_PIN = 5
L_DIR_PIN = 3
R_STEP_PIN = 6
R_DIR_PIN = 2

# constants for arduino connection
PORT = "COM9"
DIR_UP = "UP\n"
DIR_DOWN = "DOWN\n"
LINEAR_STEPPER = "LIN\n"
ANGULAR_STEPPER = "ANG\n"
TRIPLE_STEPPER_TYPES = [LINEAR_STEPPER, ANGULAR_STEPPER, "TRI\n"]
MOVING_THRESHOLD = 8

BAUD_RATE = 9600

LIORAH_PORTS = ["COM10", "COM8"]
MINHA_PORTS = ["COM29", "COM13"] # CRAZYYYYY
STROL_PORTS = ["COM10", "COM9"]
KONSTI_PORTS = ["COM3", "COM6"]
SERIAL_PORTS = LIORAH_PORTS

DEBUG = False
